name: 'Builds your Jekyll website'
description: 'Allows you to build your Jekyll website. The resulting (_site) artifact should be published using a separate action'

inputs:
  verbose:
    description: 'Enables verbose logging of the build command'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.verbose }}

branding:
  icon: 'archive'
  color: 'green'
